#ifndef __LLDWRAPPER_H__
#define __LLDWRAPPER_H__

#if defined(WIN32) || defined(WIN64)
#else
#include <dlfcn.h>

#define LoadLibrary(path)     dlopen((path), RTLD_LAZY);
#define GetProcAddress(handle,module)  dlsym((handle),(module));
#define FreeLibrary(handle)   dlclose((handle));

#define TSPLLD_PATH	"/usr/lib/libtsplld0381.so.1.0.0"
#define HINSTANCE void*

#define WINAPI
typedef void VOID;
typedef int INT;
typedef long LONG;
//typedef unsigned long ULONG;
//typedef ULONG DWORD;
typedef unsigned int* PDWORD;
typedef unsigned char UCHAR;
typedef UCHAR* PUCHAR;
typedef INT* PINT;

typedef INT   (WINAPI* FTYPE_INT_INT)(INT);
typedef INT   (WINAPI* FTYPE_INT_INT_INT)(INT,INT);
typedef INT   (WINAPI* FTYPE_INT_VOID)(VOID);
typedef INT   (WINAPI* FTYPE_INT_LONG_LONG)(LONG,LONG);
typedef INT   (WINAPI* FTYPE_INT_LONG)(LONG);
typedef INT	 (WINAPI* FTYPE_INT_LONG_ULONG_LONG)(LONG,unsigned long,LONG);
typedef INT   (WINAPI* FTYPE_INT_LONG_DOUBLE)(LONG,double);
typedef INT   (WINAPI* FTYPE_INT_LONG_LONG_DOUBLE)(LONG,LONG,double);
typedef VOID *(WINAPI* FTYPE_PVOID_VOID)(VOID);
typedef INT   (WINAPI* FTYPE_INT_PDWORD_ULONG_PDWORD)(PDWORD,unsigned long,PDWORD);
typedef INT   (WINAPI* FTYPE_INT_PUCHAR_PUCHAR)(PUCHAR,PUCHAR);
typedef INT   (WINAPI* FTYPE_INT_PUCHAR_PUCHAR_PINT_PINT_PINT_INT)(PUCHAR,PUCHAR,PINT,PINT,PINT,INT);
typedef INT   (WINAPI* FTYPE_INT_PUCHAR_PUCHAR_INT)(PUCHAR,PUCHAR,INT);
typedef INT   (WINAPI* FTYPE_INT_INT_INT_PUCHAR_INT_INT_INT)(INT,INT,PUCHAR,INT,INT,INT);
typedef VOID *(WINAPI* FTYPE_PVOID_LONG)(LONG);

#endif
#define GET_PROC(a,b,c) { b = (a)GetProcAddress(m_hInstance, c); }

FTYPE_INT_INT				TVB380_init;
FTYPE_INT_INT_INT			TVB380_open;
FTYPE_INT_VOID 				TVB380_close;
FTYPE_INT_LONG_LONG 		TVB380_SET_CONFIG;
FTYPE_INT_LONG				TVB380_IS_ENABLED_TYPE;
FTYPE_INT_VOID				TSPL_GET_BOARD_ID;
FTYPE_INT_VOID				TSPL_GET_BOARD_CONFIG_STATUS;
FTYPE_INT_VOID				TSPL_RESET_SDCON;
FTYPE_INT_LONG_LONG			TVB380_SET_MODULATOR_IF_FREQ;
FTYPE_INT_LONG_LONG			TVB380_SET_MODULATOR_SPECTRUM_INVERSION;
FTYPE_INT_LONG_ULONG_LONG	TVB380_SET_MODULATOR_FREQ;
FTYPE_INT_LONG_ULONG_LONG	TVB380_SET_MODULATOR_SYMRATE;
FTYPE_INT_LONG_DOUBLE 		TVB380_SET_MODULATOR_ATTEN_VALUE;
FTYPE_INT_LONG_LONG_DOUBLE TVB380_SET_MODULATOR_PRBS_INFO;
FTYPE_INT_LONG_LONG 		TVB380_SET_BOARD_CONFIG_STATUS;
FTYPE_INT_LONG_LONG 		TVB380_SET_MODULATOR_SDRAM_CLOCK;
FTYPE_INT_INT_INT 			TSPL_SET_SDRAM_BANK_INFO;
FTYPE_INT_INT				TSPL_SET_SDRAM_BANK_CONFIG;
FTYPE_INT_INT				TSPL_SET_SDRAM_BANK_OFFSET_CONFIG;
FTYPE_INT_INT				TSPL_SET_SDCON_MODE;
FTYPE_INT_INT				TSPL_SET_TSIO_DIRECTION;
FTYPE_INT_INT_INT			TSPL_SET_FIFO_CONTROL;
FTYPE_INT_LONG_LONG			TSPL_SET_PLAY_RATE;
FTYPE_INT_VOID				TSPL_GET_CUR_BANK_GROUP;
FTYPE_INT_VOID				TSPL_GET_DMA_STATUS;
FTYPE_PVOID_VOID			TSPL_GET_DMA_ADDR;
FTYPE_INT_PDWORD_ULONG_PDWORD TSPL_WRITE_BLOCK;
FTYPE_PVOID_LONG			TSPL_READ_BLOCK;
FTYPE_INT_VOID 				TVB380_SET_MODULATOR_INIT_CIF;
FTYPE_INT_PUCHAR_PUCHAR		TVB380_SET_MODULATOR_RUN_CIF;
FTYPE_INT_PUCHAR_PUCHAR		TSPL_DO_DEINTERLEAVING;
FTYPE_INT_PUCHAR_PUCHAR_PINT_PINT_PINT_INT	TSPL_DO_RS_DECODING;
FTYPE_INT_PUCHAR_PUCHAR_INT	TSPL_CONVERT_TO_NI;
FTYPE_INT_INT_INT_PUCHAR_INT_INT_INT TSPL_GET_SYNC_POSITION;

#endif
