//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by app.rc
//
#define STR_OUTPUT_RATE                 101
#define STR_RF_IF_OUTPUT                102
#define STR_MODULATOR                   103
#define STR_LOOP                        104
#define IDI_ICON1                       104
#define STR_TOOL                        105
#define STR_SI_PID                      106
#define IDI_ICON2                       106
#define STR_ADD_LIST                    107
#define STR_DELETE_LIST                 108
#define STR_RECORD_STREAM               109
#define STR_INPUT_SOURCE_FILE           110
#define STR_INPUT_SOURCE_ASI            111
#define STR_INPUT_SOURCE_310            112
#define STR_INPUT_SOURCE_IP_SEND        113
#define STR_INPUT_SOURCE_IP_RECV        114
#define STR_INPUT_SOURCE_IP_REC         115
#define STR_PLAY_LIST                   116
#define STR_DISK_FREE                   117
#define STR_PROGRAM                     118
#define STR_ZOOM                        119
#define STR_TS_RATE                     120
#define STR_PACKET_SIZE                 121
#define STR_PLAYBACK_TIME               122
#define STR_MODULATOR_PARAMETERS        123
#define STR_OK                          124
#define STR_CANCEL                      125
#define STR_CLOSE                       126
#define STR_ADD                         127
#define STR_DELETE                      128
#define STR_DELETE_ALL                  129
#define STR_SAVE                        130
#define STR_LOAD                        131
#define STR_UPDATE                      132
#define STR_CONTINUE                    133
#define STR_SUB_LOOP                    134
#define STR_USE_SUB_LOOP                135
#define STR_PLAYBACK_TIME_NO_UNIT       136
#define STR_START                       137
#define STR_END                         138
#define STR_USE_THE_FIXED_TS_RATE_ON_PLAYLIST 139
#define STR_SCHEDULE_TASKS              140
#define STR_SCHEDULE                    141
#define STR_WAKE_UP                     142
#define STR_DURATION                    143
#define STR_EXIT                        144
#define STR_DAY_OF_MONTH                145
#define STR_MON                         146
#define STR_TUE                         147
#define STR_WED                         148
#define STR_THR                         149
#define STR_FRI                         150
#define STR_SAT                         151
#define STR_SUN                         152
#define STR_TASKS                       153
#define STR_DAILY                       154
#define STR_WEEKLY                      155
#define STR_MONTHLY                     156
#define STR_ONCE                        157
#define STR_RF_LEVEL                    159
#define STR_ATTEN                       160
#define STR_TAT4710                     161
#define STR_USE_AMPLIFIER               162
#define STR_USE_TAT4710                 163
#define STR_CHANNEL_TABLE               164
#define STR_ENABLE_NULL_TP_OUTPUT_ON_STOP 165
#define STR_USE_NOISE_INSERTION         166
#define STR_GENERATION_MODE             167
#define STR_LOOP_ADAPTATION             168
#define STR_UDT_TIME_SETTING            169
#define STR_CHANGE_FROM_2nd_LOOP        170
#define STR_USE_CURRENT_DATE_TIME       171
#define STR_LICENSE_INPUT               172
#define STR_LICENSE_INPUT_COMMENT       173
#define STR_TMCC_PARAMETERS             174
#define STR_ISDB_T_PARAMETERS           175
#define STR_LAYER_PARAMETERS            176
#define STR_DATA_RATE                   177
#define STR_SELECTED                    178
#define STR_MULTI_MAPPING               179
#define STR_OTHER_PIDS                  180
#define STR_PRESET                      181
#define STR_TMCC_USE                    182
#define STR_PARAMS                      183
#define STR_IP_STREAMING_AV_DECODING    184
#define STR_IP_STREAMING                185
#define STR_AV_DECODING_EXPERIMENTAL    186
#define STR_OUTPUT                      187
#define STR_INPUT                       188
#define STR_SELECT_A_TARGET_TO_EDIT     189
#define STR_ACCESS_ADDRESS_PORT         190
#define STR_ADAPTOR                     191
#define STR_TYPE                        192
#define STR_MAX_TOOLTIP                 193
#define STR_DEFAULT_TOOLTIP             194
#define STR_SI_TABLE_PID_BIT_USAGE      195
#define STR_hh_mm_ss                    196
#define STR_ERROR_INJECTION             197
#define STR_LOSE_PACKET                 198
#define STR_BITS_ERROR                  199
#define STR_BYTES_ERROR                 200
#define STR_ONCE_EVERY                  201
#define STR_PACKET                      202
#define STR_PER_PACKET                  203
#define STR_ERROR_BIT_COUNT             204
#define STR_ERROR_BYTE_COUNT            205
#define STR_LOSE_PACKET_COMMENT         206
#define STR_BITS_ERROR_COMMENT          207
#define STR_BYTES_ERROR_COMMENT         208
#define STR_LICENSE_MANAGER             209
#define STR_CHECK                       210
#define STR_ENGLISH_VERSION_ONLY        211
#define STR_FACTROY_DEFAULT             212
#define STR_LICENSE_SYSTEM_COMMENT      213
#define STR_PRESET_PIDS_COMMENT         214
#define STR_SET_INPUT_BITRAT_COMMENT    215
#define STR_ISDB_T_1SEGMENT_COMMENT     216
#define STR_ISDB_T_13SEGMENT_COMMENT    217
#define STR_USE_USER_DATE_TIME          218
#define STR_PLAYBACK_RATE               219
#define STR_EST_PLAYBACK_RATE           220
#define STR_SYMBOL_RATE                 221
#define STR_USE_COMBINER                222
#define STR_COMBINER_PARAMETER          223
#define STR_EMERGENCY                   224
#define STR_RESET                       225
#define STR_SLOT                        226
#define STR_TOTAL_SLOT                  227
#define STR_TOTAL_PLAYBACKRATE          228
#define STR_MULTI_PLP                   229
#define STR_PLAYING_PLP                 230
#define STR_REPEAT                      304
#define STR_SINGLE                      305
#define STR_STOP                        306
#define STR_DEBUG_ERR                   699
#define STR_EXIT_SYSTEM                 700
#define STR_NO_FILE_TO_RECORD           798
#define STR_PLAY_FILE_SIZE_IS_ZERO      799
#define STR_SYMBOL_RATE_OUT_OF_RANGE    911
#define STR_OUT_OF_RF_RANGE             912
#define STR_UPDATE_LICENSE_DATA         913
#define STR_FAIL_TO_BACKUP_LICENSE_DATA 914
#define STR_FAIL_TO_UPDATE_LICENSE_DATA 915
#define STR_IP_RECV_OUTPUT_RATE         916
#define STR_ONCE_PLAY_MODE              917
#define STR_LOOP_PLAY_MODE              918
#define STR_TS_RATE_OUT_OF_RANGE        919
#define STR_MOUSE_OPERATION_REQUIRED    920
#define STR_REMOVE_FILE_ABORTED         921
#define STR_SELECT_INPUT_SOURCE         922
#define STR_ENTER_DELETE                923
#define STR_INPUT_SOURCE_CHANGED        924
#define STR_WAITING                     925
#define STR_PLAYING                     926
#define STR_BUFERING                    927
#define STR_DELAYING_STOPPED            928
#define STR_PLAYING_STOPPED             929
#define STR_RECODRING_STOPPED           930
#define STR_RECORDING                   931
#define STR_INPUT_BITRATE               932
#define STR_SELECT_A_DAY_OF_MONTH       933
#define STR_SELECT_A_WEEKDAYS           934
#define STR_TMCC_UPDATED                935
#define STR_REMOVE_FILE_CONFIRMED       936
#define STR_FAIL_TO_DETECT_BOARD        937
#define STR_PLAY_FIFO_FULL              938
#define STR_MODULATOR_UNLOCKED          939
#define STR_9857_PLL_UNLOCKED           940
#define STR_MODULATOR_TX_DISABLED       941
#define STR_FIFO_EMPTY                  942
#define STR_FIFO_FULL                   943
#define STR_310M_UNLOCKED               944
#define STR_ASI_UNLOCKED                945
#define STR_INVALID_DURATION_TIME       946
#define STR_INVALID_WAKE_UP_FORMAT      947
#define STR_TOO_MANY_TASKS              948
#define STR_ONLY_LAYER_A_1_SEGMENT      949
#define STR_PARTIAL_RECEPTION_CHECK     950
#define STR_LAYER_A_1_SEGMENT           951
#define STR_INVALID_TMCC_PARAMETER      952
#define STR_EXCEED_LAYER_CAPACITY       953
#define STR_FAILT_TO_ADD_TO_PLAY_LIST   954
#define STR_PLAY_LIST_FULL              955
#define STR_FILE_LIST_EMPTY             956
#define STR_FAIL_TO_REFESH_PLAY_LIST    957
#define STR_FAIL_TO_REMOVE_FILE         958
#define STR_FILE_NOT_FOUND              959
#define STR_READ_ONLY_FILE              960
#define STR_FAIL_TO_SHOW_FILE_INFO      961
#define STR_FAIL_TO_GET_FILE_SIZE       962
#define STR_FAIL_TO_CHECK_LICENSE       963
#define STR_FAIL_TO_SET_CNR             964
#define STR_FAIL_TO_SET_RF_LEVEL        965
#define STR_INVALID_FRONT_KEY_INPUT     966
#define STR_INVALID_WHEN_PLAYING_OR_RECORDING 967
#define STR_INVALID_LOOP_ADAPT          968
#define STR_INVALID_DTMB_PARAMS         969
#define STR_FAIL_TO_START_IP_STREAMING  970
#define STR_FAIL_TO_START_MONITOR_THREAD 975
#define STR_RS232C_TX_ERROR             976
#define STR_FAIL_TO_CONFIGURE_EPLD      977
#define STR_FAIL_TO_STOP_PLAY           978
#define STR_INVALID_ARGUMENT            979
#define STR_FAIL_TO_CREATE_RECORD_FILE  980
#define STR_FAIL_TO_CREATE_LOG_FILE     981
#define STR_ALTERA_FILE_READ_ERR        982
#define STR_FAIL_TO_CLOSE_TSP_DRV       983
#define STR_NO_DRV_FOR_SET_SYS          984
#define STR_FAIL_TO_STOP_DRV            985
#define STR_FAIL_TO_START_RECORD_THREAD 986
#define STR_FAIL_TO_START_PLAY_THREAD   987
#define STR_TOO_BIG_FILE_TO_WRITE_ERR   988
#define STR_NO_TS_SYNC_ERR              989
#define STR_DMAM_ALLOC_ERR              992
#define STR_DOWNLOAD_ERR                993
#define STR_DRV_ERR                     994
#define STR_FILE_READ_ERR               995
#define STR_NO_RBF                      996
#define STR_NO_DEVICE                   997
#define STR_NO_DRIVER                   998
#define STR_UNKNOWN_ERR                 999

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        118
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
