#ifndef __REG590S_H
#define __REG590S_H

#include	"lld_regs.h"

//////////////////////////////////////////////////////
static unsigned long PCI590S_ADDRESS_MAPPING[] = {
	PCI590S_REG_FRONT_232_TX,				TSP_MEM_ADDR_TXD,
	PCI590S_REG_DDS_INC,					TSP_MEM_ADDR_DDSCLOCK_INC,
	PCI590S_REG_MAX_PLAYRATE,				TSP_MEM_MAX_PLAY_RATE,
	PCI590S_REG_DRAM_BANKOFFSET,			TSP_SDRAM_BANK_CONFIG,
	PCI590S_REG_DRAM_SUB_BANKOFFSET,		TSP_SDRAM_BANK_OFFSET_CONFIG,
	PCI590S_REG_DRAM_BANKINFO,				TSP_MEM_ADDR_BANK_INFO,//???
	PCI590S_REG_MOD_COMMAND1,				TSP_MEM_ADDR_TXMODE,
	PCI590S_REG_MOD_COMMAND1,				TSP_MEM_ADDR_PRBS_MODE,
	PCI590S_REG_MOD_COMMAND1,				TSP_MEM_DVB_H_MODE_CNTL,
	PCI590S_REG_MOD_COMMAND1,				TSP_MEM_ADDR_MODULATOR_DTMB,
	PCI590S_REG_MOD_COMMAND1,				AD9857_ADDR_QPSK_CLOCK_MODE,
	PCI590S_REG_MOD_COMMAND2,				TSP_MEM_ADDR_CONSTELLATION,
	PCI590S_REG_MOD_COMMAND2,				TSP_MEM_ADDR_INTERLEAVING,
	PCI590S_REG_MOD_COMMAND2,				TSP_MEM_ADDR_PRBS_SCALE,
	PCI590S_REG_MOD_COMMAND3,				TSP_MEM_ADDR_GUARD_INTERVAL,
	PCI590S_REG_MOD_COMMAND3,				TSP_MEM_DVB_S2_PILOT_CNTL,
	PCI590S_REG_MOD_COMMAND3,				TSP_MEM_DTMB_INIT_TI_SDRAM,
	PCI590S_REG_MOD_COMMAND3,				AD9857_ADDR_QAM_CLOCK_MODE,
	PCI590S_REG_MOD_COMMAND4,				TSP_MEM_ADDR_CODE_RATE,
	PCI590S_REG_MOD_COMMAND5,				TSP_MEM_ADDR_BANDWIDTH,
	PCI590S_REG_MOD_COMMAND5,				TSP_MEM_DVB_S2_ROLL_OFF_FACTOR_CNTL,
	PCI590S_REG_MOD_COMMAND6,				TSP_MEM_ADDR_STOP_OUTPUT,
	PCI590S_REG_NOISE_GENERATOR_CTRL,		TSP_MEM_ADDR_PRBS_INFO,
	PCI590S_REG_BERT_CTRL,					TSP_MEM_BERT_STREAM_MEASUREMENT,
	PCI590S_REG_FILTER_DOWNLOAD_CONTROL,	PCI590S_REG_FILTER_DOWNLOAD_CONTROL,
	PCI590S_REG_SCALE_FACTOR,				PCI590S_REG_SCALE_FACTOR,			
	PCI590S_REG_TS_INPUT_OUTPUT_CTRL,		TSP_MEM_ADDR_TS_IO_CNTL,
	PCI590S_REG_DAC_CONTROL,				PCI590S_REG_DAC_CONTROL,
	PCI590S_REG_DAC_PLL_LOCK_CONTROL,		PCI590S_REG_DAC_PLL_LOCK_CONTROL,
	PCI590S_REG_MOD_RESET_CONTROL,			PCI590S_REG_MOD_RESET_CONTROL,//???
	PCI590S_REG_SYMBOL_CLOCK_CONTROL,		AD9852_SYMBOL_CLOCK_ADDR,
	PCI590S_REG_TRF178_PLL1_CTRL,			TRF178_PLL1_ADDR_CONTROL_REG,
	PCI590S_REG_TRF178_PLL2_CTRL,			TRF178_PLL2_ADDR_CONTROL_REG,
	PCI590S_REG_TRF178_ATTEN_CTRL,			TRF178_ATTN_ADDR_CONTROL_REG,
	PCI590S_REG_TRF178_BAND_CTRL,			TRF178_OUTPUT_BAND_CONTROL_REG,
	PCI590S_REG_UPCONV_AMP_SELECTION,		TSP_BOARD_CONFIG_INFO,
	PCI590S_REG_LED_CONTROL,				TSP_BOARD_LED_STATUS,
	PCI590S_REG_FPGA_TEST_WRITE,			TSP_MEM_ADDR_FPGA_WRITE_TEST,
	PCI590S_REG_DEMUX_BLK_TEST_CONTROL,		TSP_MEM_ADDR_DEMUX_CNTL_TEST,
	PCI590S_REG_LICENSEDATA0,				TSP_MEM_ADDR_LN_DATA_REG0,
	PCI590S_REG_LICENSEDATA1,				TSP_MEM_ADDR_LN_DATA_REG1,
	PCI590S_REG_LICENSEDATA2,				TSP_MEM_ADDR_LN_DATA_REG2,
	PCI590S_REG_LICENSEDATA3,				TSP_MEM_ADDR_LN_DATA_REG3,
	PCI590S_REG_LN_DECIPHER_CTRL,			TSP_MEM_ADDR_LN_DATA_CNTL,
	PCI590S_REG_SN_CTRL,					TSP_MEM_ADDR_Chip_SN_CNTL,
	PCI590S_REG_PRECORRECTION_CONTROL,		PCI590S_REG_PRECORRECTION_CONTROL,//???
	PCI590S_REG_PRECORRECTION_DNDATA,		PCI590S_REG_PRECORRECTION_DNDATA,//???
	PCI590S_REG_PCR_RESTAMP_CONTROL,		PCI590S_REG_PCR_RESTAMP_CONTROL,//???
	PCI590S_REG_BOARD_STATUS,				TSP_MEM_ADDR_STATUS,
	PCI590S_REG_MOD_STATUS,					TSP_MEM_ADDR_READ_PARAMS,
	PCI590S_REG_BUFFER_STATUS,				TSP_MEM_ISDBT_BUFFER_STATUS,
	PCI590S_REG_PCR_RESTAMP_STATUS,			PCI590S_REG_PCR_RESTAMP_STATUS,//???
	PCI590S_REG_FPGA_TEST_READ,				TSP_MEM_ADDR_FPGA_READ_TEST,
	PCI590S_REG_ERROR_STATUS,				TSP_MEM_TS_INPUT_STATUS,
	PCI590S_REG_PUMPING_TS_COUNTER,			TSP_MEM_TS_INPUT_COUNT,
	PCI590S_REG_FRONT_BUF_READY,			TSP_MEM_ADDR_TX_EMPTY,
	PCI590S_REG_FRONT_DATA_READ,			TSP_MEM_ADDR_RXD,
	PCI590S_REG_DAC_DATA_READ,				PCI590S_REG_DAC_DATA_READ,
	PCI590S_REG_Chip_SN0,					TSP_MEM_ADDR_Chip_SN_LO_REG,
	PCI590S_REG_Chip_SN1,					TSP_MEM_ADDR_Chip_SN_HI_REG,
	PCI590S_REG_Chip_READ_STATUS,			TSP_MEM_ADDR_Chip_STATUS_REG,
	PCI590S_REG_MODULATOR_PERMISSION,		TSP_MEM_ADDR_MOD_PERMISSION_REG,
	PCI590S_REG_ENCRYPT_SN0,				TSP_MEM_ADDR_SN_DATA_REG0,
	PCI590S_REG_ENCRYPT_SN1,				TSP_MEM_ADDR_SN_DATA_REG1,
	PCI590S_REG_ENCRYPT_SN2,				TSP_MEM_ADDR_SN_DATA_REG2,
	PCI590S_REG_ENCRYPT_SN3,				TSP_MEM_ADDR_SN_DATA_REG3,
	PCI590S_REG_BOARD_ID_OPTION,			TSP_BOARD_ID_ADDR,
	PCI590S_REG_CONFIGURE_STATUS_READ,		TSP_BOARD_CONFIG_STATUS,
	PCI590S_REG_BOARD_SECURITY,				TSP_BOARD_SECURITY,
	PCI590S_REG_MODULATOR_OPTION_STATUS,	TSP_MEM_ADDR_MODULATOR_CONFIG,
	//I/Q PLAY/CAPTURE
	PCI590S_REG_IQ_PLAY_CAPTURE_CTRL,		TSP_MEM_ADDR_IQ_PLAY_CAPTURE_CTRL,
	PCI590S_REG_IQ_PLAY_CAPTURE_FPGA_CAP,	TSP_MEM_ADDR_IQ_PLAY_CAPTURE_FPGA_CAP,
	PCI590S_REG_IQ_PLAY_CAPTURE_FPGA_BLD,	TSP_MEM_ADDR_IQ_PLAY_CAPTURE_FPGA_BLD,
	//TVB593
	PCI590S_REG_MOD_COMMAND1,				TSP_MEM_USB_DMA_DIRECTION,
	PCI590S_REG_MOD_COMMAND1,				TSP_MEM_ISDBT_MODULATOR_RESET,
	PCI590S_REG_MOD_COMMAND1,				TSP_MEM_ADDR_MH_MODE,
	PCI590S_REG_MOD_COMMAND1,				TSP_MEM_ADDR_MH_PID,
	PCI590S_REG_ISDBT_SYMBOL_CLOCK_CTRL,	TSP_MEM_ISDBT_SYMBOL_CLOCK_CTRL,
	0,0
};

static unsigned long PCI590S_ADDRESS_NON_MAPPING[] = {
	PCI590S_REG_FPGA_CONFIG,
	PCI590S_REG_RESET_COMMAND,
	PCI590S_REG_SELECT_EXT_OSC,
	PCI590S_REG_OPERATION_MODE,
	PCI590S_REG_MODULATION_OPTION,
	PCI590S_REG_FRONT_232_RX_BUF_CLR,
	PCI590S_REG_SDRAM_CLOCK_SELECTION,
	0
};

#define DO_PCI590S_ADDRESS_MAPPING(a,b,c,d)			a = 0;															\
													b = 0;															\
													while ( PCI590S_ADDRESS_MAPPING[b] > 0 )						\
													{																\
														if ( c == PCI590S_ADDRESS_MAPPING[b+1] )					\
														{															\
															a = 1;													\
															break;													\
														}															\
														b = b+2;													\
													};																\
													if ( a == 1 )													\
													{																\
														d = PCI590S_ADDRESS_MAPPING[b];								\
													}

#define DO_PCI590S_ADDRESS_NON_MAPPING(a,b,c,d)		a = 0;															\
													b = 0;															\
													while ( PCI590S_ADDRESS_NON_MAPPING[b] > 0 )					\
													{																\
														if ( c == PCI590S_ADDRESS_NON_MAPPING[b] )					\
														{															\
															a = 1;													\
															break;													\
														}															\
														++b;														\
													};																\
													if ( a == 0 )													\
													{																\
														DO_PCI590S_ADDRESS_MAPPING(a,b,c,d)							\
													}

#endif

