#ifndef __REG593_H
#define __REG593_H

#include	"lld_regs.h"


//////////////////////////////////////////////////////
static unsigned long PCI593_ADDRESS_MAPPING[] = {
	PCI593_REG_FRONT_232_TX,				TSP_MEM_ADDR_TXD,
	PCI593_REG_DDS_INC,					TSP_MEM_ADDR_DDSCLOCK_INC,
	PCI593_REG_MAX_PLAYRATE,				TSP_MEM_MAX_PLAY_RATE,
	PCI593_REG_DRAM_BANKOFFSET,			TSP_SDRAM_BANK_CONFIG,
	PCI593_REG_DRAM_SUB_BANKOFFSET,		TSP_SDRAM_BANK_OFFSET_CONFIG,
	PCI593_REG_DRAM_BANKINFO,				TSP_MEM_ADDR_BANK_INFO,//???
	PCI593_REG_MOD_COMMAND1,				TSP_MEM_ADDR_TXMODE,
	PCI593_REG_BERT_CTRL,					TSP_MEM_ADDR_PRBS_MODE,
	PCI593_REG_MOD_COMMAND1,				TSP_MEM_DVB_H_MODE_CNTL,
	PCI593_REG_MOD_COMMAND1,				TSP_MEM_ADDR_MODULATOR_DTMB,
	PCI593_REG_MOD_COMMAND1,				AD9857_ADDR_QPSK_CLOCK_MODE,
	PCI593_REG_MOD_COMMAND2,				TSP_MEM_ADDR_CONSTELLATION,
	PCI593_REG_MOD_COMMAND2,				TSP_MEM_ADDR_INTERLEAVING,
	PCI593_REG_BERT_CTRL,					TSP_MEM_ADDR_PRBS_SCALE,
	PCI593_REG_MOD_COMMAND3,				TSP_MEM_ADDR_GUARD_INTERVAL,
	PCI593_REG_MOD_COMMAND3,				TSP_MEM_DVB_S2_PILOT_CNTL,
	PCI593_REG_MOD_COMMAND3,				TSP_MEM_DTMB_INIT_TI_SDRAM,
	PCI593_REG_MOD_COMMAND3,				AD9857_ADDR_QAM_CLOCK_MODE,
	PCI593_REG_MOD_COMMAND4,				TSP_MEM_ADDR_CODE_RATE,
	PCI593_REG_MOD_COMMAND5,				TSP_MEM_ADDR_BANDWIDTH,
	PCI593_REG_MOD_COMMAND5,				TSP_MEM_DVB_S2_ROLL_OFF_FACTOR_CNTL,
	PCI593_REG_MOD_COMMAND6,				TSP_MEM_ADDR_STOP_OUTPUT,
	PCI593_REG_NOISE_GENERATOR_CTRL,		TSP_MEM_ADDR_PRBS_INFO,
	PCI593_REG_BERT_CTRL,					TSP_MEM_BERT_STREAM_MEASUREMENT,
	PCI593_REG_FILTER_DOWNLOAD_CONTROL,	PCI593_REG_FILTER_DOWNLOAD_CONTROL,
	PCI593_REG_SCALE_FACTOR,				PCI593_REG_SCALE_FACTOR,			
	PCI593_REG_TS_INPUT_OUTPUT_CTRL,		TSP_MEM_ADDR_TS_IO_CNTL,
	PCI593_REG_DAC_CONTROL,				AD9857_ADDR_REG_CONTROL,	//	PCI593_REG_DAC_CONTROL,
	PCI593_REG_DAC_PLL_LOCK_CONTROL,		PCI593_REG_DAC_PLL_LOCK_CONTROL,
	PCI593_REG_MOD_RESET_CONTROL,			PCI593_REG_MOD_RESET_CONTROL,//???
	PCI593_REG_SYMBOL_CLOCK_CONTROL,		AD9852_SYMBOL_CLOCK_ADDR,
	PCI593_REG_TRF178_PLL1_CTRL,			TRF178_PLL1_ADDR_CONTROL_REG,	//	same _ADR_591_UPCONV_PLL1_CTRL
	PCI593_REG_TRF178_PLL2_CTRL,			TRF178_PLL2_ADDR_CONTROL_REG,	//	same _ADR_591_UPCONV_PLL2_CTRL
	PCI593_REG_TRF178_ATTEN_CTRL,			TRF178_ATTN_ADDR_CONTROL_REG,	//	same _ADR_591_UPCONV_SW_ATTN_AMP_CTRL
	PCI593_REG_TRF178_BAND_CTRL,			TRF178_OUTPUT_BAND_CONTROL_REG,
	PCI593_REG_UPCONV_AMP_SELECTION,		TSP_BOARD_CONFIG_INFO,
	PCI593_REG_LED_CONTROL,				TSP_BOARD_LED_STATUS,
	PCI593_REG_FPGA_TEST_WRITE,			TSP_MEM_ADDR_FPGA_WRITE_TEST,
	PCI593_REG_DEMUX_BLK_TEST_CONTROL,		TSP_MEM_ADDR_DEMUX_CNTL_TEST,
	PCI593_REG_LICENSEDATA0,				TSP_MEM_ADDR_LN_DATA_REG0,
	PCI593_REG_LICENSEDATA1,				TSP_MEM_ADDR_LN_DATA_REG1,
	PCI593_REG_LICENSEDATA2,				TSP_MEM_ADDR_LN_DATA_REG2,
	PCI593_REG_LICENSEDATA3,				TSP_MEM_ADDR_LN_DATA_REG3,
	PCI593_REG_LN_DECIPHER_CTRL,			TSP_MEM_ADDR_LN_DATA_CNTL,
	PCI593_REG_SN_CTRL,					TSP_MEM_ADDR_Chip_SN_CNTL,
	PCI593_REG_PRECORRECTION_CONTROL,		PCI593_REG_PRECORRECTION_CONTROL,//???
	PCI593_REG_PRECORRECTION_DNDATA,		PCI593_REG_PRECORRECTION_DNDATA,//???
	PCI593_REG_PCR_RESTAMP_CONTROL,		PCI593_REG_PCR_RESTAMP_CONTROL,//???
	PCI593_REG_BOARD_STATUS,				TSP_MEM_ADDR_STATUS,
	PCI593_REG_MOD_STATUS,					TSP_MEM_ADDR_READ_PARAMS,
	PCI593_REG_BUFFER_STATUS,				TSP_MEM_ISDBT_BUFFER_STATUS,
	PCI593_REG_PCR_RESTAMP_STATUS,			PCI593_REG_PCR_RESTAMP_STATUS,//???
	PCI593_REG_FPGA_TEST_READ,				TSP_MEM_ADDR_FPGA_READ_TEST,
	PCI593_REG_ERROR_STATUS,				TSP_MEM_TS_INPUT_STATUS,
	PCI593_REG_PUMPING_TS_COUNTER,			TSP_MEM_TS_INPUT_COUNT,
	PCI593_REG_FRONT_BUF_READY,			TSP_MEM_ADDR_TX_EMPTY,
	PCI593_REG_FRONT_DATA_READ,			TSP_MEM_ADDR_RXD,
	PCI593_REG_DAC_DATA_READ,				PCI593_REG_DAC_DATA_READ,
	PCI593_REG_Chip_SN0,					TSP_MEM_ADDR_Chip_SN_LO_REG,
	PCI593_REG_Chip_SN1,					TSP_MEM_ADDR_Chip_SN_HI_REG,
	PCI593_REG_Chip_READ_STATUS,			TSP_MEM_ADDR_Chip_STATUS_REG,
	PCI593_REG_MODULATOR_PERMISSION,		TSP_MEM_ADDR_MOD_PERMISSION_REG,
	PCI593_REG_ENCRYPT_SN0,				TSP_MEM_ADDR_SN_DATA_REG0,
	PCI593_REG_ENCRYPT_SN1,				TSP_MEM_ADDR_SN_DATA_REG1,
	PCI593_REG_ENCRYPT_SN2,				TSP_MEM_ADDR_SN_DATA_REG2,
	PCI593_REG_ENCRYPT_SN3,				TSP_MEM_ADDR_SN_DATA_REG3,
	PCI593_REG_BOARD_ID_OPTION,			TSP_BOARD_ID_ADDR,
	PCI593_REG_CONFIGURE_STATUS_READ,		TSP_BOARD_CONFIG_STATUS,
	PCI593_REG_BOARD_SECURITY,				TSP_BOARD_SECURITY,
	PCI593_REG_MODULATOR_OPTION_STATUS,	TSP_MEM_ADDR_MODULATOR_CONFIG,
	//I/Q PLAY/CAPTURE
	PCI593_REG_IQ_PLAY_CAPTURE_CTRL,		TSP_MEM_ADDR_IQ_PLAY_CAPTURE_CTRL,
	PCI593_REG_IQ_PLAY_CAPTURE_FPGA_CAP,	TSP_MEM_ADDR_IQ_PLAY_CAPTURE_FPGA_CAP,
	PCI593_REG_IQ_PLAY_CAPTURE_FPGA_BLD,	TSP_MEM_ADDR_IQ_PLAY_CAPTURE_FPGA_BLD,
	//TVB593
	PCI593_REG_MOD_COMMAND1,			TSP_MEM_USB_DMA_DIRECTION,
	PCI593_REG_MOD_COMMAND1,			TSP_MEM_ISDBT_MODULATOR_RESET,
	PCI593_REG_MOD_COMMAND1,			TSP_MEM_ADDR_MH_MODE,
	PCI593_REG_MOD_COMMAND1,			TSP_MEM_ADDR_MH_PID,
	PCI593_REG_ISDBT_SYMBOL_CLOCK_CTRL,	TSP_MEM_ISDBT_SYMBOL_CLOCK_CTRL,
	PCI593_REG_IQ_PLAY_CAPTURE_FPGA_READ, PCI593_REG_IQ_PLAY_CAPTURE_FPGA_READ,
	//2011/4/13 
	PCI593_REG_MOD_COMMAND1,			_FPGA_REG___MOD_CMD_1,
	PCI593_REG_MOD_COMMAND1,			_FPGA_REG___MOD_CMD_2,
	PCI593_REG_MOD_COMMAND1,			_FPGA_REG___MOD_CMD_3,
	PCI593_REG_MOD_COMMAND1,			_FPGA_REG___MOD_CMD_4,
	PCI593_REG_MOD_COMMAND1,			_FPGA_REG___MOD_CMD_5,
	PCI593_REG_MOD_COMMAND1,			_FPGA_REG___MOD_CMD_6,
	0,0
};

typedef	enum
{
	_mRF_RESET_CTRL	=	0x50100,
	_mRF_OPERATION_MODE_TS_IO_CTRL	=	0x50300,
	_mRF_PLAY_RATE_CTRL_2	=	0x50600,
	_mRF_PLAY_RATE_CTRL_3	=	0x50700,
	_mRF_PLAY_RATE_CTRL_4	=	0x50800,
	_mRF_STREAM_TAG	=	0x51300,
	_mRF_MODULATOR_PARAMETER_2	=	0x52100,
	_mRF_MODULATOR_PARAMETER_3	=	0x52200,
	_mRF_MODULATOR_PARAMETER_4	=	0x52300,
	_mRF_MODULATOR_DDS_TABLE_DNLOAD	=	0x52800,
	_mRF_MODULATOR_DDS_CTRL	=	0x52900,
	_mRF_BERT_NOISE_GENERATION_CTRL2	=	0x53400,
	_mRF_MODULATOR_SCALE_FACTOR_CTRL2	=	0x53700,
	_mRF_BERT_NOISE_GENERATION_CTRL3	=	0x53800,
	_mRF_MODULATOR_SCALE_FACTOR_CTRL3	=	0x53B00,
	_mRF_BERT_NOISE_GENERATION_CTRL4	=	0x53C00,
	_mRF_MODULATOR_SCALE_FACTOR_CTRL4	=	0x53F00,
	_mRF_Buffer_Status	=	0x60200,
	_mRF_Stream_Buffer_Status_1	=	0x64000,
	_mRF_Stream_Buffer_Status_2	=	0x64100,
	_mRF_Stream_Buffer_Status_3	=	0x64200,
	_mRF_Stream_Buffer_Status_4	=	0x64300,
	_mRF_Capture_Buffer_Status	=	0x64800,
}	___REG__MAP_to_SUPPORT_MULTI_RF___;

static unsigned long PCI593_ADDRESS_NON_MAPPING[] = {
	PCI593_REG_FPGA_CONFIG,
	PCI593_REG_RESET_COMMAND,
	PCI593_REG_SELECT_EXT_OSC,
	PCI593_REG_OPERATION_MODE,
	PCI593_REG_MODULATION_OPTION,
	PCI593_REG_FRONT_232_RX_BUF_CLR,
	PCI593_REG_SDRAM_CLOCK_SELECTION,

	_mRF_RESET_CTRL,
	_mRF_OPERATION_MODE_TS_IO_CTRL,
	_mRF_PLAY_RATE_CTRL_2,
	_mRF_PLAY_RATE_CTRL_3,
	_mRF_PLAY_RATE_CTRL_4,
	_mRF_STREAM_TAG,
	_mRF_MODULATOR_PARAMETER_2,
	_mRF_MODULATOR_PARAMETER_3,
	_mRF_MODULATOR_PARAMETER_4,
	_mRF_MODULATOR_DDS_TABLE_DNLOAD,
	_mRF_MODULATOR_DDS_CTRL,
	_mRF_BERT_NOISE_GENERATION_CTRL2,
	_mRF_MODULATOR_SCALE_FACTOR_CTRL2,
	_mRF_BERT_NOISE_GENERATION_CTRL3,
	_mRF_MODULATOR_SCALE_FACTOR_CTRL3,
	_mRF_BERT_NOISE_GENERATION_CTRL4,
	_mRF_MODULATOR_SCALE_FACTOR_CTRL4,
	_mRF_Buffer_Status,
	_mRF_Stream_Buffer_Status_1,
	_mRF_Stream_Buffer_Status_2,
	_mRF_Stream_Buffer_Status_3,
	_mRF_Stream_Buffer_Status_4,
	_mRF_Capture_Buffer_Status,
	0
};

#define DO_PCI593_ADDRESS_MAPPING(a,b,c,d)			a = 0;															\
													b = 0;															\
													while ( PCI593_ADDRESS_MAPPING[b] > 0 )							\
													{																\
														if ( c == PCI593_ADDRESS_MAPPING[b+1] )						\
														{															\
															a = 1;													\
															break;													\
														}															\
														b = b+2;													\
													};																\
													if ( a == 1 )													\
													{																\
														d = PCI593_ADDRESS_MAPPING[b];								\
													}

#define DO_PCI593_ADDRESS_NON_MAPPING(a,b,c,d)		a = 0;															\
													b = 0;															\
													while ( PCI593_ADDRESS_NON_MAPPING[b] > 0 )						\
													{																\
														if ( c == PCI593_ADDRESS_NON_MAPPING[b] )					\
														{															\
															a = 1;													\
															break;													\
														}															\
														++b;														\
													};																\
													if ( a == 0 )													\
													{																\
														DO_PCI593_ADDRESS_MAPPING(a,b,c,d)							\
													}

#endif
